### ISSUE TITLE
Change interface: replace dataFile with dest as an option

### ISSUE THREAD

**Issue by Grawl** [Ser-Gen/postcss-data-packer#7]
I think will be cool to use your plugin with more plain and simple way.

Instead of creating new subtask (at least for Grunt) we can just specify `dest` path for CSS with `data` and remove all data from `src` by default.

```js
data:{
	options:{
		map:false,
		processors:[
			dataPaker({
				dest:'css/main_data.css'
			})
		]
	},
	src:'css/main.css'
}
```

Easy.

And if we will turn `keepData` to `true` then all `data` will stay in `main.css`

**Comment by Ser-Gen** [comment]
Looks great! I will look into it soon.

**Comment by goschevski** [comment]
Any updates on this?

**Comment by Ser-Gen** [comment]
Hope to make this in next two weeks.

**Comment by Ser-Gen** [comment]
Late for three days, but [added](https://github.com/Ser-Gen/postcss-data-packer#dest-default-false) in 1.1.0.

**Comment by Grawl** [comment]
Cool :sunglasses:

**Comment by goschevski** [comment]
Thanks!
