### ISSUE TITLE
Use PostCSS 5 API

### ISSUE THREAD

**Issue by TrySound** [Ser-Gen/postcss-data-packer#9]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by Ser-Gen** [comment]
[1.1.0](https://github.com/Ser-Gen/postcss-data-packer/releases/tag/1.1.0) using PostCSS 5 API.
Need to add tests ([#9](https://github.com/Ser-Gen/postcss-data-packer/issues/9)).
